trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - task: Docker@2
    displayName: BACKEND | Build and push to container repository
    inputs:
      command: buildAndPush
      containerRegistry: Registry PrenotazioneNRS
      repository: simonecorazza/prenotazioninrs
      buildContext: ./backend
      tags: |
        $(Build.BuildId)
  - task: Docker@2
    displayName: FRONTEND | Build and push to container repository
    inputs:
      command: buildAndPush
      containerRegistry: Registry PrenotazioneNRS
      repository: simonecorazza/prenotazioninrs
      buildContext: ./frontend
      tags: |
        $(Build.BuildId)
