trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: BACKEND
  steps:
  - task: Docker@2
    displayName:  Build and push to container repository
    inputs:
      command: buildAndPush
      containerRegistry: Registry PrenotazioneNRS
      repository: simonecorazza/prenotazioninrs
      buildContext: ./backend
      tags: |
        backend-$(Build.BuildId)
- job: FRONTEND
  steps:
  - task: Docker@2
    displayName: Build and push to container repository
    inputs:
      command: buildAndPush
      containerRegistry: Registry PrenotazioneNRS
      repository: simonecorazza/prenotazioninrs
      buildContext: ./frontend
      tags: |
        frontend-$(Build.BuildId)
