services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PrenotazioniNRS
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"