@host = http://localhost:5195

DELETE {{host}}/api/v1/PuliziaSede/Rimuovimi/10
Accept: application/json
X-Nome-Utente: Simone

###

POST {{host}}/api/v1/PuliziaSede/Aggiungimi/10
Accept: application/json
X-Nome-Utente: Marco

###

POST {{host}}/api/v1/AttivitaOrdinaria/Aggiungimi/Apertura/2025-01-21
Accept: application/json
X-Nome-Utente: Simone3

###

POST {{host}}/api/v1/AttivitaOrdinaria/Aggiungimi/Chiusura/2025-01-21
Accept: application/json
X-Nome-Utente: Simone3

###

POST {{host}}/api/v1/AttivitaOrdinaria/Rimuovimi/Apertura/2025-01-21
Accept: application/json
X-Nome-Utente: Simone3

###

POST {{host}}/api/v1/AttivitaOrdinaria/Rimuovimi/Chiusura/2025-01-21
Accept: application/json
X-Nome-Utente: Simone

###

GET {{host}}/api/v1/Calendario?from=2025-01-01&to=2025-06-01
Accept: application/json
X-Nome-Utente: Simone